/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/_store'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as StoreIndexRouteImport } from './routes/_store/index'
import { Route as StoreAboutRouteImport } from './routes/_store/about'
import { Route as StoreCartRouteImport } from './routes/_store/cart'
import { Route as StoreCheckoutRouteImport } from './routes/_store/checkout'
import { Route as StoreContactRouteImport } from './routes/_store/contact'
import { Route as StoreKidsRouteImport } from './routes/_store/kids'
import { Route as StoreMenRouteImport } from './routes/_store/men'
import { Route as StoreOffersRouteImport } from './routes/_store/offers'
import { Route as StoreShopRouteImport } from './routes/_store/shop'
import { Route as StoreWishlistRouteImport } from './routes/_store/wishlist'
import { Route as StoreWomenRouteImport } from './routes/_store/women'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAdvertisementsRouteImport } from './routes/admin/advertisements'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as StoreOrderCodeRouteImport } from './routes/_store/order.$code'
import { Route as StoreProductSlugRouteImport } from './routes/_store/product.$slug'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const StoreRoute = StoreRouteImport.update({
  id: '/_store',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StoreRoute,
} as any)
const StoreAboutRoute = StoreAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => StoreRoute,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => StoreRoute,
} as any)
const StoreContactRoute = StoreContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => StoreRoute,
} as any)
const StoreKidsRoute = StoreKidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => StoreRoute,
} as any)
const StoreMenRoute = StoreMenRouteImport.update({
  id: '/men',
  path: '/men',
  getParentRoute: () => StoreRoute,
} as any)
const StoreOffersRoute = StoreOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => StoreRoute,
} as any)
const StoreShopRoute = StoreShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StoreRoute,
} as any)
const StoreWishlistRoute = StoreWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => StoreRoute,
} as any)
const StoreWomenRoute = StoreWomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => StoreRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdvertisementsRoute = AdminAdvertisementsRouteImport.update({
  id: '/advertisements',
  path: '/advertisements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const StoreOrderCodeRoute = StoreOrderCodeRouteImport.update({
  id: '/order/$code',
  path: '/order/$code',
  getParentRoute: () => StoreRoute,
} as any)
const StoreProductSlugRoute = StoreProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => StoreRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof StoreAboutRoute
  '/cart': typeof StoreCartRoute
  '/checkout': typeof StoreCheckoutRoute
  '/contact': typeof StoreContactRoute
  '/kids': typeof StoreKidsRoute
  '/men': typeof StoreMenRoute
  '/offers': typeof StoreOffersRoute
  '/shop': typeof StoreShopRoute
  '/wishlist': typeof StoreWishlistRoute
  '/women': typeof StoreWomenRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/order/$code': typeof StoreOrderCodeRoute
  '/product/$slug': typeof StoreProductSlugRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/about': typeof StoreAboutRoute
  '/cart': typeof StoreCartRoute
  '/checkout': typeof StoreCheckoutRoute
  '/contact': typeof StoreContactRoute
  '/kids': typeof StoreKidsRoute
  '/men': typeof StoreMenRoute
  '/offers': typeof StoreOffersRoute
  '/shop': typeof StoreShopRoute
  '/wishlist': typeof StoreWishlistRoute
  '/women': typeof StoreWomenRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/': typeof StoreIndexRoute
  '/admin': typeof AdminIndexRoute
  '/order/$code': typeof StoreOrderCodeRoute
  '/product/$slug': typeof StoreProductSlugRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_store': typeof StoreRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_store/about': typeof StoreAboutRoute
  '/_store/cart': typeof StoreCartRoute
  '/_store/checkout': typeof StoreCheckoutRoute
  '/_store/contact': typeof StoreContactRoute
  '/_store/kids': typeof StoreKidsRoute
  '/_store/men': typeof StoreMenRoute
  '/_store/offers': typeof StoreOffersRoute
  '/_store/shop': typeof StoreShopRoute
  '/_store/wishlist': typeof StoreWishlistRoute
  '/_store/women': typeof StoreWomenRoute
  '/admin/advertisements': typeof AdminAdvertisementsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/_store/': typeof StoreIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_store/order/$code': typeof StoreOrderCodeRoute
  '/_store/product/$slug': typeof StoreProductSlugRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/kids'
    | '/men'
    | '/offers'
    | '/shop'
    | '/wishlist'
    | '/women'
    | '/admin/advertisements'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/'
    | '/order/$code'
    | '/product/$slug'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/kids'
    | '/men'
    | '/offers'
    | '/shop'
    | '/wishlist'
    | '/women'
    | '/admin/advertisements'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/'
    | '/admin'
    | '/order/$code'
    | '/product/$slug'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/_store'
    | '/admin'
    | '/_store/about'
    | '/_store/cart'
    | '/_store/checkout'
    | '/_store/contact'
    | '/_store/kids'
    | '/_store/men'
    | '/_store/offers'
    | '/_store/shop'
    | '/_store/wishlist'
    | '/_store/women'
    | '/admin/advertisements'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/_store/'
    | '/admin/'
    | '/_store/order/$code'
    | '/_store/product/$slug'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StoreRoute: typeof StoreRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_store': {
      id: '/_store'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_store/': {
      id: '/_store/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/about': {
      id: '/_store/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof StoreAboutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/cart': {
      id: '/_store/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/checkout': {
      id: '/_store/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/contact': {
      id: '/_store/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof StoreContactRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/kids': {
      id: '/_store/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof StoreKidsRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/men': {
      id: '/_store/men'
      path: '/men'
      fullPath: '/men'
      preLoaderRoute: typeof StoreMenRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/offers': {
      id: '/_store/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof StoreOffersRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/shop': {
      id: '/_store/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof StoreShopRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/wishlist': {
      id: '/_store/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof StoreWishlistRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/women': {
      id: '/_store/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof StoreWomenRouteImport
      parentRoute: typeof StoreRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/advertisements': {
      id: '/admin/advertisements'
      path: '/advertisements'
      fullPath: '/admin/advertisements'
      preLoaderRoute: typeof AdminAdvertisementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_store/order/$code': {
      id: '/_store/order/$code'
      path: '/order/$code'
      fullPath: '/order/$code'
      preLoaderRoute: typeof StoreOrderCodeRouteImport
      parentRoute: typeof StoreRoute
    }
    '/_store/product/$slug': {
      id: '/_store/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof StoreProductSlugRouteImport
      parentRoute: typeof StoreRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StoreRouteChildren {
  StoreAboutRoute: typeof StoreAboutRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreContactRoute: typeof StoreContactRoute
  StoreKidsRoute: typeof StoreKidsRoute
  StoreMenRoute: typeof StoreMenRoute
  StoreOffersRoute: typeof StoreOffersRoute
  StoreShopRoute: typeof StoreShopRoute
  StoreWishlistRoute: typeof StoreWishlistRoute
  StoreWomenRoute: typeof StoreWomenRoute
  StoreIndexRoute: typeof StoreIndexRoute
  StoreOrderCodeRoute: typeof StoreOrderCodeRoute
  StoreProductSlugRoute: typeof StoreProductSlugRoute
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreAboutRoute: StoreAboutRoute,
  StoreCartRoute: StoreCartRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreContactRoute: StoreContactRoute,
  StoreKidsRoute: StoreKidsRoute,
  StoreMenRoute: StoreMenRoute,
  StoreOffersRoute: StoreOffersRoute,
  StoreShopRoute: StoreShopRoute,
  StoreWishlistRoute: StoreWishlistRoute,
  StoreWomenRoute: StoreWomenRoute,
  StoreIndexRoute: StoreIndexRoute,
  StoreOrderCodeRoute: StoreOrderCodeRoute,
  StoreProductSlugRoute: StoreProductSlugRoute,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

interface AdminRouteChildren {
  AdminAdvertisementsRoute: typeof AdminAdvertisementsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdvertisementsRoute: AdminAdvertisementsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StoreRoute: StoreRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
